[package]
name = "kajiya-imgui"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kajiya = { path = "../kajiya" }

ash-imgui = { path = "../ash-imgui" }
imgui = "0.12.0"
imgui-winit-support = "0.13.0"
log = "0.4.32"
parking_lot = "0.12.5"
winit = { version = "0.30.13", features = ["rwh_06"] }
