[workspace]
resolver = "2"
members = [
    "crates/bin/bake",
    "crates/bin/hello",
    "crates/bin/view",

    "crates/lib/kajiya-asset",
    "crates/lib/kajiya-asset-pipe",
    "crates/lib/kajiya-backend",
    "crates/lib/kajiya-imgui",
    "crates/lib/kajiya-rg",
    "crates/lib/kajiya-simple",
    "crates/lib/kajiya",

    "crates/lib/ash-imgui",
]

exclude = [
    "crates/lib/rust-shaders",
    "crates/lib/rust-shaders-shared",
    "crates/bin/rust-shader-builder",
    "crates/lib/ngx_dlss"
]

[profile.release]
debug = 1
