[package]
name = "kajiya-simple"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kajiya = { path = "../kajiya" }
kajiya-imgui = { path = "../kajiya-imgui", optional = true }

anyhow = "1.0"
glam = { version = "0.30", features = ["serde"] }
log = "0.4"
puffin = { version = "0.20.0" }
turbosloth = { git = "https://github.com/h3r2tic/turbosloth.git", rev = "92030af" }
winit = { version = "0.30.13", features = ["rwh_06"] }

puffin_http = { version = "0.17.0", optional = true }
imgui = { version = "0.12.0", optional = true }

[features]
dear-imgui = [
    "imgui",
    "kajiya-imgui",
]
puffin-server = [
    "puffin_http",
]
winit_serde = [
    "winit/serde",
]
