[package]
name = "kajiya"
version = "0.2.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kajiya-asset = { path = "../kajiya-asset" }
kajiya-backend = { path = "../kajiya-backend" }
kajiya-rg = { path = "../kajiya-rg" }
rust-shaders-shared = { path = "../rust-shaders-shared" }

anyhow = "1.0"
array-init = "2.1.0"
blue-noise-sampler = "0.1"
bytemuck = "1.9.1"
chrono = "0.4.45"
exr = "1.74.0"
fern = { version = "0.7.1", features = ["colored"] }
glam = "0.30"
half = { version = "2.7.1", features = ["bytemuck"] }
image = { version = "0.25.10", default-features = false, features = ["gif", "jpeg", "ico", "png", "pnm", "tga", "tiff", "webp", "bmp", "hdr"] }
log = "0.4"
memmap2 = "0.9.10"
parking_lot = "0.12.5"
radiant = "0.3"
smol = "2.0.2"
turbosloth = { git = "https://github.com/h3r2tic/turbosloth.git", rev = "92030af" }

ngx_dlss = { path = "../ngx_dlss", optional = true }
wchar = { version = "0.11.1", optional = true }

easy-parallel = "3.3.1"

[features]
default = []
dlss = [ "ngx_dlss", "kajiya-backend/dlss", "dep:wchar" ]
